INSERT INTO card_catalog (card_item_id, card_name) VALUES (15001, 'â€œMineur Sombreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15002, 'â€œForgeron Sombreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15003, 'â€œBoulanger Sombreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15004, 'â€œBandit du clan des Roublardsâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15005, 'â€œBandit Manchotâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15006, 'â€œBraconnierâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15007, 'â€œKrtekâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15008, 'â€œVil Smisseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15009, 'â€œBwork Mageâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15010, 'â€œChevaucheur de Karneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15011, 'â€œBwork Archerâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15012, 'â€œGobelinâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15013, 'â€œBworkâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15014, 'â€œBworketteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15015, 'â€œMama Bworkâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15016, 'â€œBwork ElÃ©mental de Feuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15017, 'â€œBwork ElÃ©mental d\\''Eauâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15018, 'â€œBwork ElÃ©mental d\\''Airâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15019, 'â€œBwork ElÃ©mental de Terreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15020, 'â€œCybworkâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15021, 'â€œBworkerâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15022, 'â€œWabbitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15023, 'â€œBlack Wabbitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15024, 'â€œBlack Tiwabbitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15025, 'â€œTiwabbit Kiafinâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15026, 'â€œTiwabbitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15027, 'â€œWo Wabbitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15028, 'â€œGrand Pa Wabbitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15029, 'â€œWabbit Squeletteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15030, 'â€œWobotâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15031, 'â€œWabbit Gmâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15032, 'â€œWa Wabbitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15033, 'â€œDragOeuf DorÃ© immature â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15034, 'â€œDragOeuf Blancâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15035, 'â€œDragOeuf Noir immatureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15036, 'â€œDragOeuf DorÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15037, 'â€œDragOeuf de Saphirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15038, 'â€œDragOeuf Noirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15039, 'â€œDragOeuf Blanc immatureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15040, 'â€œDragOeuf Noir EveillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15041, 'â€œDragOeuf Blanc Ã©veillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15042, 'â€œDragOeuf DorÃ© Ã©veillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15043, 'â€œDragOeuf de Saphir Ã©veillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15044, 'â€œCoquille Explosiveâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15045, 'â€œDragOeuf de Saphir immatureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15046, 'â€œDragoss Noirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15047, 'â€œDragoss Noir EveillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15048, 'â€œDragoss Blanc EveillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15049, 'â€œDragoss DorÃ© EveillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15050, 'â€œDragoss de Saphirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15051, 'â€œDragoss Blancâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15052, 'â€œDragoss DorÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15053, 'â€œDragoss de Saphir EveillÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15054, 'â€œDragoeuf Guerrierâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15055, 'â€œDragueuseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15056, 'â€œDragoeuf Volantâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15057, 'â€œCrocabuliaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15058, 'â€œGrozillaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15059, 'â€œGrasmeraâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15060, 'â€œGelÃ©e Bleueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15061, 'â€œGelÃ©e Mentheâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15062, 'â€œGelÃ©e Fraiseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15063, 'â€œGelÃ©e Citronâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15064, 'â€œGelÃ©e Royale Bleueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15065, 'â€œGelÃ©e Royale Mentheâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15066, 'â€œGelÃ©e Royale Fraiseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15067, 'â€œGelÃ©e Royale Citronâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15068, 'â€œTofu MalÃ©fiqueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15069, 'â€œVampireâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15070, 'â€œSouris Griseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15071, 'â€œLa Ouassingueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15072, 'â€œLe Ouassingueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15073, 'â€œGargrouilleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15074, 'â€œCitwouilleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15075, 'â€œOniâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15076, 'â€œMaÃ®tre Vampireâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15077, 'â€œNoeulâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15078, 'â€œKwoanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15079, 'â€œVampire Dupyrâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15080, 'â€œDark Vladâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15081, 'â€œBouftouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15082, 'â€œBoufton Blancâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15083, 'â€œBoufton Noirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15084, 'â€œChef de Guerre Bouftouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15085, 'â€œBouftou d\\''Halouineâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15086, 'â€œBallotin le Bouftouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15087, 'â€œBouftou Royalâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15088, 'â€œBouftou des Cavernesâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15089, 'â€œBoufcoulâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15090, 'â€œTournesol Sauvageâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15091, 'â€œRose DÃ©moniaqueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15092, 'â€œPissenlit Diaboliqueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15093, 'â€œRose Obscureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15094, 'â€œTournesol AffamÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15095, 'â€œPiou Violetâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15096, 'â€œPiou Rougeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15097, 'â€œPiou Vertâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15098, 'â€œPiou Bleuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15099, 'â€œPiou Roseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15100, 'â€œPiou Jauneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15101, 'â€œLarve Bleueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15102, 'â€œLarve Verteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15103, 'â€œLarve Orangeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15104, 'â€œLarve Saphirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15105, 'â€œLarve Rubisâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15106, 'â€œLarve Emeraudeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15107, 'â€œLarve DorÃ©eâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15108, 'â€œShin Larveâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15109, 'â€œBwak de feuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15110, 'â€œBwak de terreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15111, 'â€œBwak d\\''airâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15112, 'â€œBwak d\\''eauâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15113, 'â€œKwak du Ventâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15114, 'â€œKwak de Flammeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15115, 'â€œKwak de Glaceâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15116, 'â€œKwak de Terreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15117, 'â€œCraquebouleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15118, 'â€œCraqueleurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15119, 'â€œCraqueleur des plainesâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15120, 'â€œMÃ©ga Craqueleurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15121, 'â€œCraqueleur LÃ©gendaireâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15122, 'â€œCochon de Laitâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15123, 'â€œCochon de Farleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15124, 'â€œDon Duss Angâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15125, 'â€œDon Dorganâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15126, 'â€œDragon Cochonâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15127, 'â€œChaferâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15128, 'â€œChafer Archerâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15129, 'â€œRibâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15130, 'â€œChafer Invisibleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15131, 'â€œChafer Lancierâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15132, 'â€œChafer d\\''Ã©liteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15133, 'â€œChafer Fantassinâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15134, 'â€œChafer Archer Mauditâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15135, 'â€œChafer Lamicelâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15136, 'â€œChafer Mauditâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15137, 'â€œAboubâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15138, 'â€œAmlubâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15139, 'â€œCodemâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15140, 'â€œGinkâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15141, 'â€œKirevamâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15142, 'â€œLet Emoliugâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15143, 'â€œNebgibâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15144, 'â€œNipulâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15145, 'â€œOsurcâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15146, 'â€œSusejâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15147, 'â€œIdemasâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15148, 'â€œTeilemrakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15149, 'â€œDopeul Dark Vladâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15150, 'â€œFourbasseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15151, 'â€œTrukikolâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15152, 'â€œGloutovoreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15153, 'â€œKanniboul Archerâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15154, 'â€œKanniboul Thierryâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15155, 'â€œKanniboul Javâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15156, 'â€œKanniboul Sarbakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15157, 'â€œDarkli Moonâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15158, 'â€œMoonâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15159, 'â€œTikokokoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15160, 'â€œKokokoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15161, 'â€œNodKokoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15162, 'â€œTortue Rougeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15163, 'â€œTortue Bleueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15164, 'â€œTortue Verteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15165, 'â€œTortue Jauneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15166, 'â€œBoombaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15167, 'â€œNakunbraâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15168, 'â€œCanon Dorfâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15169, 'â€œLe Chouqueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15170, 'â€œAbraknydeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15171, 'â€œTronknydeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15172, 'â€œAbrakneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15173, 'â€œAraknotronâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15174, 'â€œAbraknyde Sombreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15175, 'â€œAbrakne Sombreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15176, 'â€œBranche Invocatriceâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15177, 'â€œBranche Soignanteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15178, 'â€œAbraknyde Ancestralâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15179, 'â€œChÃªne Mouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15180, 'â€œBlop Cocoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15181, 'â€œBlop Indigoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15182, 'â€œBlop Griotteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15183, 'â€œBlop Reinetteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15184, 'â€œBiblop Indigoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15185, 'â€œBiblop Cocoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15186, 'â€œBiblop Griotteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15187, 'â€œBiblop Reinetteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15188, 'â€œGloutoblopâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15189, 'â€œBlopignonâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15190, 'â€œTronkoblopâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15191, 'â€œBlop Coco Royalâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15192, 'â€œBlop Griotte Royalâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15193, 'â€œBlop Indigo Royalâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15194, 'â€œBlop Reinette Royalâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15195, 'â€œBlop Multicolore Royalâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15196, 'â€œSerpentinâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15197, 'â€œCavalier Porkassâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15198, 'â€œBerger Porkassâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15199, 'â€œSouris verteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15200, 'â€œSanglier Des Plainesâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15201, 'â€œKanigrouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15202, 'â€œGarde Havouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15203, 'â€œTireur d\\''Ã‰liteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15204, 'â€œDisciple de Turorteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15205, 'â€œPalidane le PlatinÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15206, 'â€œMage CÃ©lesteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15207, 'â€œCraqueleur CÃ©lesteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15208, 'â€œCramodyâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15209, 'â€œMihssihâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15210, 'â€œHarasâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15211, 'â€œYllibâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15212, 'â€œIlyzaelleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15213, 'â€œScorbuteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15214, 'â€œCroc Glandâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15215, 'â€œKolÃ©ratâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15216, 'â€œOuginakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15217, 'â€œCroc Gland enragÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15218, 'â€œFantÃ´me Ardentâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15219, 'â€œFantÃ´me Braveâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15220, 'â€œFantÃ´me Arepoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15221, 'â€œQu\\''Tanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15222, 'â€œPetit DÃ©mon Rapideâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15223, 'â€œEnvoyÃ© des Abyssesâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15224, 'â€œSorcier DÃ©monâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15225, 'â€œSbire de Qu\\''Tanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15226, 'â€œRat d\\''Egoutantâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15227, 'â€œChaman d\\''Egoutantâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15228, 'â€œRat d\\''Egoutant maladeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15229, 'â€œMilirat d\\''Egoutant maladeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15230, 'â€œRat d\\''Hyoactifâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15231, 'â€œRat de Maraisâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15232, 'â€œRat Batteurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15233, 'â€œRat Klureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15234, 'â€œRat Basherâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15235, 'â€œRat Bajoieâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15236, 'â€œRat Crocâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15237, 'â€œRat Noirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15238, 'â€œRat Blancâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15239, 'â€œRaphaelaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15240, 'â€œDonatellaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15241, 'â€œMichelangelaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15242, 'â€œLeonardawaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15243, 'â€œSphincter Cellâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15244, 'â€œFrakacia Leukocytineâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15245, 'â€œOgivol Scalarcinâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15246, 'â€œFouduglen L\\''Ã©cureuilâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15247, 'â€œMarzwel le Gobelinâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15248, 'â€œAermyne \\''Braco\\'' Scalptarasâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15249, 'â€œPadgref DemoÃ«lâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15250, 'â€œRok Gnorokâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15251, 'â€œMusha L\\''Oniâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15252, 'â€œEratz le Revendicateurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15253, 'â€œNomekop Le Crapoteurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15254, 'â€œEdasse Le Trouble FÃªteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15255, 'â€œQil Bilâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15256, 'â€œZatoÃ¯shwanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15257, 'â€œUk\\''Not\\''Allagâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15258, 'â€œScarafeuille Rougeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15259, 'â€œScarafeuille Bleuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15260, 'â€œScarafeuille Vertâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15261, 'â€œScarafeuille Blancâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15262, 'â€œFlammÃ¨che Feuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15263, 'â€œFlammÃ¨che Eauâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15264, 'â€œFlammÃ¨che Terreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15265, 'â€œFlammÃ¨che Airâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15266, 'â€œScarafeuille Noirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15267, 'â€œScarafeuille Immatureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15268, 'â€œScarabosse DorÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15269, 'â€œGardienne des Egoutsâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15270, 'â€œAraknawaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15271, 'â€œTouchparakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15272, 'â€œArakneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15273, 'â€œArakne Maladeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15274, 'â€œArakne Agressiveâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15275, 'â€œArakne Majeureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15276, 'â€œMilimulouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15277, 'â€œMulouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15278, 'â€œTroollâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15279, 'â€œMeulouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15280, 'â€œPrespicâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15281, 'â€œSanglierâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15282, 'â€œMoskitoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15283, 'â€œL\\''homme Oursâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15284, 'â€œMilimilouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15285, 'â€œCrocodailleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15286, 'â€œBooâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15287, 'â€œChef Crocodailleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15288, 'â€œCrocoburioâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15289, 'â€œFantÃ´me Crocodailleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15290, 'â€œChamp Champâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15291, 'â€œChampa Vertâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15292, 'â€œChampa Rougeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15293, 'â€œChampa Bleuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15294, 'â€œChampa Marronâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15295, 'â€œMaÃ®tre Boletâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15296, 'â€œTromperelleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15297, 'â€œChampaknydeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15298, 'â€œChampodonteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15299, 'â€œChampmaneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15300, 'â€œChampbisâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15301, 'â€œChamp Ã  Gnonsâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15302, 'â€œOugahâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15303, 'â€œTofuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15304, 'â€œTofu Maladeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15305, 'â€œTofu Noirâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15306, 'â€œTofouneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15307, 'â€œTofukazâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15308, 'â€œTofuzmoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15309, 'â€œTofu Ventripotentâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15310, 'â€œTofu d\\''Halouineâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15311, 'â€œBatofuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15312, 'â€œTofu Royalâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15313, 'â€œCorbacâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15314, 'â€œCorbac ApprivoisÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15315, 'â€œBuveurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15316, 'â€œRenarboâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15317, 'â€œMaÃ®tre Corbacâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15318, 'â€œDragodinde Amande Sauvageâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15319, 'â€œDragodinde Rousse Sauvageâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15320, 'â€œDragodinde DorÃ©e Sauvageâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15321, 'â€œDoK Alakoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15322, 'â€œKoalak Immatureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15323, 'â€œKoalak Indigoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15324, 'â€œKoalak Cocoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15325, 'â€œKoalak Griotteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15326, 'â€œKoalak Reinetteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15327, 'â€œMama Koalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15328, 'â€œWarko Marronâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15329, 'â€œWorketteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15330, 'â€œPiralakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15331, 'â€œKoalak Forestierâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15332, 'â€œPÃ©keualakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15333, 'â€œDrakoalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15334, 'â€œFauchalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15335, 'â€œKoulosseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15336, 'â€œGuerrier Koalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15337, 'â€œMaÃ®tre Koalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15338, 'â€œChevaucheur Koalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15339, 'â€œMomie Koalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15340, 'â€œFossoyeur Koalakâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15341, 'â€œKoalak Sanguinâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15342, 'â€œWarko Violetâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15343, 'â€œKoalak Faroucheâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15344, 'â€œEmeraudeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15345, 'â€œSaphiraâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15346, 'â€œDÃ©gelÃ©eâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15347, 'â€œRubiseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15348, 'â€œDiamantineâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15349, 'â€œSkeunkâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15350, 'â€œGaminoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15351, 'â€œSerpiplumeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15352, 'â€œScaratosâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15353, 'â€œMinoskitoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15354, 'â€œMandrineâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15355, 'â€œKramÃ©lÃ©honâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15356, 'â€œMominotorâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15357, 'â€œDÃ©minobouleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15358, 'â€œMinotororâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15359, 'â€œMinototâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15360, 'â€œCrabeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15361, 'â€œPichon Orangeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15362, 'â€œPichon Bleuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15363, 'â€œPichon Blancâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15364, 'â€œPichon Vertâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15365, 'â€œEtoile de la Mer d\\''Asseâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15366, 'â€œPichon Klouneâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15367, 'â€œRaul Mopsâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15368, 'â€œMoumouleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15369, 'â€œMob l\\''Epongeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15370, 'â€œBitouf des Plainesâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15371, 'â€œCraqueleur Poliâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15372, 'â€œCraqueboule Poliâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15373, 'â€œMufafahâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15374, 'â€œKidoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15375, 'â€œKilibrissâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15376, 'â€œSilf le Rasboul Majeurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15377, 'â€œCrustorail KouraÃ§aoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15378, 'â€œCrustorail Maliboutâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15379, 'â€œCrustorail Passaohâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15380, 'â€œCrustorail Moritoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15381, 'â€œPalmifleur KouraÃ§aoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15382, 'â€œPalmifleur Maliboutâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15383, 'â€œPalmifleur Passaohâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15384, 'â€œPalmifleur Moritoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15385, 'â€œCorailleurâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15386, 'â€œCorailleur Magistralâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15387, 'â€œTourbassingueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15388, 'â€œBourbassingueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15389, 'â€œLe Ouassingue EntourbÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15390, 'â€œRoissingueâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15391, 'â€œKralamoure GÃ©antâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15392, 'â€œFloribondeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15393, 'â€œBitouf Sombreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15394, 'â€œBroutureâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15395, 'â€œFÃ©corceâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15396, 'â€œChiendentâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15397, 'â€œAbrakleur Sombreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15398, 'â€œNerbeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15399, 'â€œTynril ConsternÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15400, 'â€œTynril DÃ©concertÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15401, 'â€œTynril Perfideâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15402, 'â€œTynril Ahuriâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15403, 'â€œBitouf AÃ©rienâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15404, 'â€œPoolayâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15405, 'â€œAbrakleur Clairâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15406, 'â€œKaskargoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15407, 'â€œMeupetteâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15408, 'â€œKimboâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15409, 'â€œSparoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15410, 'â€œBarbroussaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15411, 'â€œLe Flibâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15412, 'â€œGourlo le Terribleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15413, 'â€œGamine Zothâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15414, 'â€œGuerrier Zothâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15415, 'â€œDisciple Zothâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15416, 'â€œSergent Zothâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15417, 'â€œMaÃ®tre Zothâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15418, 'â€œManitou Zothâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15419, 'â€œCooleuvreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15420, 'â€œBulbifloreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15421, 'â€œBulbuissonâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15422, 'â€œBamboutoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15423, 'â€œBulbambouâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15424, 'â€œBulbigâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15425, 'â€œBambouto SacrÃ©â€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15426, 'â€œTanuki Chanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15427, 'â€œKitsou Nakwaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15428, 'â€œKitsou Nereâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15429, 'â€œKitsou Naeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15430, 'â€œKitsou Nufeuâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15431, 'â€œPandawa Ivreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15432, 'â€œPandalette Ivreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15433, 'â€œTanukouÃ¯ Sanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15434, 'â€œPanditâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15435, 'â€œPandikaze aÃ©rienâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15436, 'â€œPandikaze vertigeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15437, 'â€œPandikwakazeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15438, 'â€œPandulkazeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15439, 'â€œGuerrier Pandikazeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15440, 'â€œPanduleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15441, 'â€œPandikazeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15442, 'â€œMaÃ®tre Pandoreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15443, 'â€œPandoreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15444, 'â€œZillaâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15445, 'â€œYokai Firefouxâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15446, 'â€œSoryo Firefouxâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15447, 'â€œMaho Firefouxâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15448, 'â€œLÃ©opardoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15449, 'â€œPÃ©ki PÃ©kiâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15450, 'â€œFantÃ´me Pandikazeâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15451, 'â€œFantÃ´me Maho Firefouxâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15452, 'â€œFantÃ´me Soryo Firefouxâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15453, 'â€œFantÃ´me LÃ©opardoâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15454, 'â€œFantÃ´me Yokai Firefouxâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15455, 'â€œFantÃ´me TanukouÃ¯ Sanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15456, 'â€œFantÃ´me Panduleâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15457, 'â€œFantÃ´me Tanuki Chanâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15458, 'â€œFantÃ´me Pandoreâ€');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15459, 'â€œCoffre Maudit du Flibâ€');
