INSERT INTO card_catalog (card_item_id, card_name) VALUES (15001, 'â€œMineur Sombreâ€ - No.001');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15002, 'â€œForgeron Sombreâ€ - No.002');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15003, 'â€œBoulanger Sombreâ€ - No.003');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15004, 'â€œBandit du clan des Roublardsâ€ - No.004');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15005, 'â€œBandit Manchotâ€ - No.005');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15006, 'â€œBraconnierâ€ - No.006');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15007, 'â€œKrtekâ€ - No.007');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15008, 'â€œVil Smisseâ€ - No.008');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15009, 'â€œBwork Mageâ€ - No.009');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15010, 'â€œChevaucheur de Karneâ€ - No.010');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15011, 'â€œBwork Archerâ€ - No.011');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15012, 'â€œGobelinâ€ - No.012');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15013, 'â€œBworkâ€ - No.013');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15014, 'â€œBworketteâ€ - No.014');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15015, 'â€œMama Bworkâ€ - No.015');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15016, 'â€œBwork ElÃ©mental de Feuâ€ - No.016');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15017, 'â€œBwork ElÃ©mental d\\''Eauâ€ - No.017');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15018, 'â€œBwork ElÃ©mental d\\''Airâ€ - No.018');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15019, 'â€œBwork ElÃ©mental de Terreâ€ - No.019');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15020, 'â€œCybworkâ€ - No.020');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15021, 'â€œBworkerâ€ - No.021');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15022, 'â€œWabbitâ€ - No.022');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15023, 'â€œBlack Wabbitâ€ - No.023');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15024, 'â€œBlack Tiwabbitâ€ - No.024');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15025, 'â€œTiwabbit Kiafinâ€ - No.025');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15026, 'â€œTiwabbitâ€ - No.026');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15027, 'â€œWo Wabbitâ€ - No.027');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15028, 'â€œGrand Pa Wabbitâ€ - No.028');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15029, 'â€œWabbit Squeletteâ€ - No.029');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15030, 'â€œWobotâ€ - No.030');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15031, 'â€œWabbit Gmâ€ - No.031');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15032, 'â€œWa Wabbitâ€ - No.032');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15033, 'â€œDragOeuf DorÃ© immature â€ - No.033');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15034, 'â€œDragOeuf Blancâ€ - No.034');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15035, 'â€œDragOeuf Noir immatureâ€ - No.035');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15036, 'â€œDragOeuf DorÃ©â€ - No.036');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15037, 'â€œDragOeuf de Saphirâ€ - No.037');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15038, 'â€œDragOeuf Noirâ€ - No.038');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15039, 'â€œDragOeuf Blanc immatureâ€ - No.039');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15040, 'â€œDragOeuf Noir EveillÃ©â€ - No.040');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15041, 'â€œDragOeuf Blanc Ã©veillÃ©â€ - No.041');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15042, 'â€œDragOeuf DorÃ© Ã©veillÃ©â€ - No.042');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15043, 'â€œDragOeuf de Saphir Ã©veillÃ©â€ - No.043');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15044, 'â€œCoquille Explosiveâ€ - No.044');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15045, 'â€œDragOeuf de Saphir immatureâ€ - No.045');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15046, 'â€œDragoss Noirâ€ - No.046');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15047, 'â€œDragoss Noir EveillÃ©â€ - No.047');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15048, 'â€œDragoss Blanc EveillÃ©â€ - No.048');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15049, 'â€œDragoss DorÃ© EveillÃ©â€ - No.049');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15050, 'â€œDragoss de Saphirâ€ - No.050');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15051, 'â€œDragoss Blancâ€ - No.051');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15052, 'â€œDragoss DorÃ©â€ - No.052');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15053, 'â€œDragoss de Saphir EveillÃ©â€ - No.053');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15054, 'â€œDragoeuf Guerrierâ€ - No.054');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15055, 'â€œDragueuseâ€ - No.055');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15056, 'â€œDragoeuf Volantâ€ - No.056');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15057, 'â€œCrocabuliaâ€ - No.057');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15058, 'â€œGrozillaâ€ - No.058');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15059, 'â€œGrasmeraâ€ - No.059');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15060, 'â€œGelÃ©e Bleueâ€ - No.060');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15061, 'â€œGelÃ©e Mentheâ€ - No.061');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15062, 'â€œGelÃ©e Fraiseâ€ - No.062');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15063, 'â€œGelÃ©e Citronâ€ - No.063');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15064, 'â€œGelÃ©e Royale Bleueâ€ - No.064');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15065, 'â€œGelÃ©e Royale Mentheâ€ - No.065');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15066, 'â€œGelÃ©e Royale Fraiseâ€ - No.066');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15067, 'â€œGelÃ©e Royale Citronâ€ - No.067');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15068, 'â€œTofu MalÃ©fiqueâ€ - No.068');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15069, 'â€œVampireâ€ - No.069');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15070, 'â€œSouris Griseâ€ - No.070');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15071, 'â€œLa Ouassingueâ€ - No.071');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15072, 'â€œLe Ouassingueâ€ - No.072');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15073, 'â€œGargrouilleâ€ - No.073');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15074, 'â€œCitwouilleâ€ - No.074');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15075, 'â€œOniâ€ - No.075');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15076, 'â€œMaÃ®tre Vampireâ€ - No.076');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15077, 'â€œNoeulâ€ - No.077');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15078, 'â€œKwoanâ€ - No.078');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15079, 'â€œVampire Dupyrâ€ - No.079');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15080, 'â€œDark Vladâ€ - No.080');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15081, 'â€œBouftouâ€ - No.081');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15082, 'â€œBoufton Blancâ€ - No.082');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15083, 'â€œBoufton Noirâ€ - No.083');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15084, 'â€œChef de Guerre Bouftouâ€ - No.084');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15085, 'â€œBouftou d\\''Halouineâ€ - No.085');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15086, 'â€œBallotin le Bouftouâ€ - No.086');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15087, 'â€œBouftou Royalâ€ - No.087');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15088, 'â€œBouftou des Cavernesâ€ - No.088');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15089, 'â€œBoufcoulâ€ - No.089');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15090, 'â€œTournesol Sauvageâ€ - No.090');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15091, 'â€œRose DÃ©moniaqueâ€ - No.091');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15092, 'â€œPissenlit Diaboliqueâ€ - No.092');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15093, 'â€œRose Obscureâ€ - No.093');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15094, 'â€œTournesol AffamÃ©â€ - No.094');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15095, 'â€œPiou Violetâ€ - No.095');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15096, 'â€œPiou Rougeâ€ - No.096');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15097, 'â€œPiou Vertâ€ - No.097');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15098, 'â€œPiou Bleuâ€ - No.098');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15099, 'â€œPiou Roseâ€ - No.099');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15100, 'â€œPiou Jauneâ€ - No.100');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15101, 'â€œLarve Bleueâ€ - No.101');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15102, 'â€œLarve Verteâ€ - No.102');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15103, 'â€œLarve Orangeâ€ - No.103');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15104, 'â€œLarve Saphirâ€ - No.104');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15105, 'â€œLarve Rubisâ€ - No.105');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15106, 'â€œLarve Emeraudeâ€ - No.106');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15107, 'â€œLarve DorÃ©eâ€ - No.107');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15108, 'â€œShin Larveâ€ - No.108');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15109, 'â€œBwak de feuâ€ - No.109');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15110, 'â€œBwak de terreâ€ - No.110');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15111, 'â€œBwak d\\''airâ€ - No.111');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15112, 'â€œBwak d\\''eauâ€ - No.112');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15113, 'â€œKwak du Ventâ€ - No.113');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15114, 'â€œKwak de Flammeâ€ - No.114');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15115, 'â€œKwak de Glaceâ€ - No.115');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15116, 'â€œKwak de Terreâ€ - No.116');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15117, 'â€œCraquebouleâ€ - No.117');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15118, 'â€œCraqueleurâ€ - No.118');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15119, 'â€œCraqueleur des plainesâ€ - No.119');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15120, 'â€œMÃ©ga Craqueleurâ€ - No.120');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15121, 'â€œCraqueleur LÃ©gendaireâ€ - No.121');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15122, 'â€œCochon de Laitâ€ - No.122');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15123, 'â€œCochon de Farleâ€ - No.123');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15124, 'â€œDon Duss Angâ€ - No.124');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15125, 'â€œDon Dorganâ€ - No.125');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15126, 'â€œDragon Cochonâ€ - No.126');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15127, 'â€œChaferâ€ - No.127');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15128, 'â€œChafer Archerâ€ - No.128');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15129, 'â€œRibâ€ - No.129');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15130, 'â€œChafer Invisibleâ€ - No.130');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15131, 'â€œChafer Lancierâ€ - No.131');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15132, 'â€œChafer d\\''Ã©liteâ€ - No.132');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15133, 'â€œChafer Fantassinâ€ - No.133');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15134, 'â€œChafer Archer Mauditâ€ - No.134');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15135, 'â€œChafer Lamicelâ€ - No.135');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15136, 'â€œChafer Mauditâ€ - No.136');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15137, 'â€œAboubâ€ - No.137');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15138, 'â€œAmlubâ€ - No.138');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15139, 'â€œCodemâ€ - No.139');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15140, 'â€œGinkâ€ - No.140');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15141, 'â€œKirevamâ€ - No.141');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15142, 'â€œLet Emoliugâ€ - No.142');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15143, 'â€œNebgibâ€ - No.143');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15144, 'â€œNipulâ€ - No.144');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15145, 'â€œOsurcâ€ - No.145');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15146, 'â€œSusejâ€ - No.146');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15147, 'â€œIdemasâ€ - No.147');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15148, 'â€œTeilemrakâ€ - No.148');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15149, 'â€œDopeul Dark Vladâ€ - No.149');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15150, 'â€œFourbasseâ€ - No.150');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15151, 'â€œTrukikolâ€ - No.151');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15152, 'â€œGloutovoreâ€ - No.152');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15153, 'â€œKanniboul Archerâ€ - No.153');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15154, 'â€œKanniboul Thierryâ€ - No.154');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15155, 'â€œKanniboul Javâ€ - No.155');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15156, 'â€œKanniboul Sarbakâ€ - No.156');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15157, 'â€œDarkli Moonâ€ - No.157');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15158, 'â€œMoonâ€ - No.158');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15159, 'â€œTikokokoâ€ - No.159');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15160, 'â€œKokokoâ€ - No.160');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15161, 'â€œNodKokoâ€ - No.161');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15162, 'â€œTortue Rougeâ€ - No.162');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15163, 'â€œTortue Bleueâ€ - No.163');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15164, 'â€œTortue Verteâ€ - No.164');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15165, 'â€œTortue Jauneâ€ - No.165');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15166, 'â€œBoombaâ€ - No.166');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15167, 'â€œNakunbraâ€ - No.167');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15168, 'â€œCanon Dorfâ€ - No.168');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15169, 'â€œLe Chouqueâ€ - No.169');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15170, 'â€œAbraknydeâ€ - No.170');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15171, 'â€œTronknydeâ€ - No.171');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15172, 'â€œAbrakneâ€ - No.172');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15173, 'â€œAraknotronâ€ - No.173');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15174, 'â€œAbraknyde Sombreâ€ - No.174');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15175, 'â€œAbrakne Sombreâ€ - No.175');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15176, 'â€œBranche Invocatriceâ€ - No.176');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15177, 'â€œBranche Soignanteâ€ - No.177');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15178, 'â€œAbraknyde Ancestralâ€ - No.178');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15179, 'â€œChÃªne Mouâ€ - No.179');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15180, 'â€œBlop Cocoâ€ - No.180');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15181, 'â€œBlop Indigoâ€ - No.181');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15182, 'â€œBlop Griotteâ€ - No.182');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15183, 'â€œBlop Reinetteâ€ - No.183');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15184, 'â€œBiblop Indigoâ€ - No.184');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15185, 'â€œBiblop Cocoâ€ - No.185');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15186, 'â€œBiblop Griotteâ€ - No.186');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15187, 'â€œBiblop Reinetteâ€ - No.187');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15188, 'â€œGloutoblopâ€ - No.188');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15189, 'â€œBlopignonâ€ - No.189');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15190, 'â€œTronkoblopâ€ - No.190');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15191, 'â€œBlop Coco Royalâ€ - No.191');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15192, 'â€œBlop Griotte Royalâ€ - No.192');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15193, 'â€œBlop Indigo Royalâ€ - No.193');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15194, 'â€œBlop Reinette Royalâ€ - No.194');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15195, 'â€œBlop Multicolore Royalâ€ - No.195');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15196, 'â€œSerpentinâ€ - No.196');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15197, 'â€œCavalier Porkassâ€ - No.197');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15198, 'â€œBerger Porkassâ€ - No.198');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15199, 'â€œSouris verteâ€ - No.199');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15200, 'â€œSanglier Des Plainesâ€ - No.200');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15201, 'â€œKanigrouâ€ - No.201');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15202, 'â€œGarde Havouâ€ - No.202');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15203, 'â€œTireur d\\''Ã‰liteâ€ - No.203');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15204, 'â€œDisciple de Turorteâ€ - No.204');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15205, 'â€œPalidane le PlatinÃ©â€ - No.205');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15206, 'â€œMage CÃ©lesteâ€ - No.206');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15207, 'â€œCraqueleur CÃ©lesteâ€ - No.207');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15208, 'â€œCramodyâ€ - No.208');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15209, 'â€œMihssihâ€ - No.209');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15210, 'â€œHarasâ€ - No.210');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15211, 'â€œYllibâ€ - No.211');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15212, 'â€œIlyzaelleâ€ - No.212');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15213, 'â€œScorbuteâ€ - No.213');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15214, 'â€œCroc Glandâ€ - No.214');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15215, 'â€œKolÃ©ratâ€ - No.215');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15216, 'â€œOuginakâ€ - No.216');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15217, 'â€œCroc Gland enragÃ©â€ - No.217');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15218, 'â€œFantÃ´me Ardentâ€ - No.218');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15219, 'â€œFantÃ´me Braveâ€ - No.219');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15220, 'â€œFantÃ´me Arepoâ€ - No.220');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15221, 'â€œQu\\''Tanâ€ - No.221');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15222, 'â€œPetit DÃ©mon Rapideâ€ - No.222');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15223, 'â€œEnvoyÃ© des Abyssesâ€ - No.223');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15224, 'â€œSorcier DÃ©monâ€ - No.224');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15225, 'â€œSbire de Qu\\''Tanâ€ - No.225');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15226, 'â€œRat d\\''Egoutantâ€ - No.226');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15227, 'â€œChaman d\\''Egoutantâ€ - No.227');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15228, 'â€œRat d\\''Egoutant maladeâ€ - No.228');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15229, 'â€œMilirat d\\''Egoutant maladeâ€ - No.229');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15230, 'â€œRat d\\''Hyoactifâ€ - No.230');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15231, 'â€œRat de Maraisâ€ - No.231');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15232, 'â€œRat Batteurâ€ - No.232');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15233, 'â€œRat Klureâ€ - No.233');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15234, 'â€œRat Basherâ€ - No.234');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15235, 'â€œRat Bajoieâ€ - No.235');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15236, 'â€œRat Crocâ€ - No.236');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15237, 'â€œRat Noirâ€ - No.237');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15238, 'â€œRat Blancâ€ - No.238');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15239, 'â€œRaphaelaâ€ - No.239');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15240, 'â€œDonatellaâ€ - No.240');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15241, 'â€œMichelangelaâ€ - No.241');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15242, 'â€œLeonardawaâ€ - No.242');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15243, 'â€œSphincter Cellâ€ - No.243');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15244, 'â€œFrakacia Leukocytineâ€ - No.244');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15245, 'â€œOgivol Scalarcinâ€ - No.245');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15246, 'â€œFouduglen L\\''Ã©cureuilâ€ - No.246');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15247, 'â€œMarzwel le Gobelinâ€ - No.247');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15248, 'â€œAermyne \\''Braco\\'' Scalptarasâ€ - No.248');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15249, 'â€œPadgref DemoÃ«lâ€ - No.249');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15250, 'â€œRok Gnorokâ€ - No.250');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15251, 'â€œMusha L\\''Oniâ€ - No.251');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15252, 'â€œEratz le Revendicateurâ€ - No.252');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15253, 'â€œNomekop Le Crapoteurâ€ - No.253');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15254, 'â€œEdasse Le Trouble FÃªteâ€ - No.254');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15255, 'â€œQil Bilâ€ - No.255');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15256, 'â€œZatoÃ¯shwanâ€ - No.256');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15257, 'â€œUk\\''Not\\''Allagâ€ - No.257');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15258, 'â€œScarafeuille Rougeâ€ - No.258');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15259, 'â€œScarafeuille Bleuâ€ - No.259');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15260, 'â€œScarafeuille Vertâ€ - No.260');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15261, 'â€œScarafeuille Blancâ€ - No.261');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15262, 'â€œFlammÃ¨che Feuâ€ - No.262');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15263, 'â€œFlammÃ¨che Eauâ€ - No.263');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15264, 'â€œFlammÃ¨che Terreâ€ - No.264');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15265, 'â€œFlammÃ¨che Airâ€ - No.265');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15266, 'â€œScarafeuille Noirâ€ - No.266');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15267, 'â€œScarafeuille Immatureâ€ - No.267');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15268, 'â€œScarabosse DorÃ©â€ - No.268');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15269, 'â€œGardienne des Egoutsâ€ - No.269');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15270, 'â€œAraknawaâ€ - No.270');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15271, 'â€œTouchparakâ€ - No.271');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15272, 'â€œArakneâ€ - No.272');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15273, 'â€œArakne Maladeâ€ - No.273');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15274, 'â€œArakne Agressiveâ€ - No.274');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15275, 'â€œArakne Majeureâ€ - No.275');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15276, 'â€œMilimulouâ€ - No.276');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15277, 'â€œMulouâ€ - No.277');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15278, 'â€œTroollâ€ - No.278');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15279, 'â€œMeulouâ€ - No.279');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15280, 'â€œPrespicâ€ - No.280');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15281, 'â€œSanglierâ€ - No.281');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15282, 'â€œMoskitoâ€ - No.282');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15283, 'â€œL\\''homme Oursâ€ - No.283');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15284, 'â€œMilimilouâ€ - No.284');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15285, 'â€œCrocodailleâ€ - No.285');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15286, 'â€œBooâ€ - No.286');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15287, 'â€œChef Crocodailleâ€ - No.287');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15288, 'â€œCrocoburioâ€ - No.288');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15289, 'â€œFantÃ´me Crocodailleâ€ - No.289');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15290, 'â€œChamp Champâ€ - No.290');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15291, 'â€œChampa Vertâ€ - No.291');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15292, 'â€œChampa Rougeâ€ - No.292');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15293, 'â€œChampa Bleuâ€ - No.293');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15294, 'â€œChampa Marronâ€ - No.294');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15295, 'â€œMaÃ®tre Boletâ€ - No.295');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15296, 'â€œTromperelleâ€ - No.296');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15297, 'â€œChampaknydeâ€ - No.297');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15298, 'â€œChampodonteâ€ - No.298');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15299, 'â€œChampmaneâ€ - No.299');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15300, 'â€œChampbisâ€ - No.300');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15301, 'â€œChamp Ã  Gnonsâ€ - No.301');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15302, 'â€œOugahâ€ - No.302');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15303, 'â€œTofuâ€ - No.303');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15304, 'â€œTofu Maladeâ€ - No.304');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15305, 'â€œTofu Noirâ€ - No.305');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15306, 'â€œTofouneâ€ - No.306');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15307, 'â€œTofukazâ€ - No.307');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15308, 'â€œTofuzmoâ€ - No.308');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15309, 'â€œTofu Ventripotentâ€ - No.309');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15310, 'â€œTofu d\\''Halouineâ€ - No.310');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15311, 'â€œBatofuâ€ - No.311');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15312, 'â€œTofu Royalâ€ - No.312');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15313, 'â€œCorbacâ€ - No.313');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15314, 'â€œCorbac ApprivoisÃ©â€ - No.314');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15315, 'â€œBuveurâ€ - No.315');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15316, 'â€œRenarboâ€ - No.316');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15317, 'â€œMaÃ®tre Corbacâ€ - No.317');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15318, 'â€œDragodinde Amande Sauvageâ€ - No.318');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15319, 'â€œDragodinde Rousse Sauvageâ€ - No.319');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15320, 'â€œDragodinde DorÃ©e Sauvageâ€ - No.320');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15321, 'â€œDoK Alakoâ€ - No.321');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15322, 'â€œKoalak Immatureâ€ - No.322');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15323, 'â€œKoalak Indigoâ€ - No.323');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15324, 'â€œKoalak Cocoâ€ - No.324');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15325, 'â€œKoalak Griotteâ€ - No.325');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15326, 'â€œKoalak Reinetteâ€ - No.326');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15327, 'â€œMama Koalakâ€ - No.327');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15328, 'â€œWarko Marronâ€ - No.328');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15329, 'â€œWorketteâ€ - No.329');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15330, 'â€œPiralakâ€ - No.330');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15331, 'â€œKoalak Forestierâ€ - No.331');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15332, 'â€œPÃ©keualakâ€ - No.332');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15333, 'â€œDrakoalakâ€ - No.333');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15334, 'â€œFauchalakâ€ - No.334');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15335, 'â€œKoulosseâ€ - No.335');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15336, 'â€œGuerrier Koalakâ€ - No.336');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15337, 'â€œMaÃ®tre Koalakâ€ - No.337');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15338, 'â€œChevaucheur Koalakâ€ - No.338');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15339, 'â€œMomie Koalakâ€ - No.339');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15340, 'â€œFossoyeur Koalakâ€ - No.340');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15341, 'â€œKoalak Sanguinâ€ - No.341');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15342, 'â€œWarko Violetâ€ - No.342');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15343, 'â€œKoalak Faroucheâ€ - No.343');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15344, 'â€œEmeraudeâ€ - No.344');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15345, 'â€œSaphiraâ€ - No.345');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15346, 'â€œDÃ©gelÃ©eâ€ - No.346');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15347, 'â€œRubiseâ€ - No.347');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15348, 'â€œDiamantineâ€ - No.348');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15349, 'â€œSkeunkâ€ - No.349');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15350, 'â€œGaminoâ€ - No.350');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15351, 'â€œSerpiplumeâ€ - No.351');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15352, 'â€œScaratosâ€ - No.352');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15353, 'â€œMinoskitoâ€ - No.353');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15354, 'â€œMandrineâ€ - No.354');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15355, 'â€œKramÃ©lÃ©honâ€ - No.355');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15356, 'â€œMominotorâ€ - No.356');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15357, 'â€œDÃ©minobouleâ€ - No.357');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15358, 'â€œMinotororâ€ - No.358');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15359, 'â€œMinototâ€ - No.359');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15360, 'â€œCrabeâ€ - No.360');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15361, 'â€œPichon Orangeâ€ - No.361');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15362, 'â€œPichon Bleuâ€ - No.362');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15363, 'â€œPichon Blancâ€ - No.363');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15364, 'â€œPichon Vertâ€ - No.364');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15365, 'â€œEtoile de la Mer d\\''Asseâ€ - No.365');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15366, 'â€œPichon Klouneâ€ - No.366');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15367, 'â€œRaul Mopsâ€ - No.367');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15368, 'â€œMoumouleâ€ - No.368');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15369, 'â€œMob l\\''Epongeâ€ - No.369');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15370, 'â€œBitouf des Plainesâ€ - No.370');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15371, 'â€œCraqueleur Poliâ€ - No.371');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15372, 'â€œCraqueboule Poliâ€ - No.372');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15373, 'â€œMufafahâ€ - No.373');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15374, 'â€œKidoâ€ - No.374');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15375, 'â€œKilibrissâ€ - No.375');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15376, 'â€œSilf le Rasboul Majeurâ€ - No.376');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15377, 'â€œCrustorail KouraÃ§aoâ€ - No.377');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15378, 'â€œCrustorail Maliboutâ€ - No.378');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15379, 'â€œCrustorail Passaohâ€ - No.379');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15380, 'â€œCrustorail Moritoâ€ - No.380');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15381, 'â€œPalmifleur KouraÃ§aoâ€ - No.381');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15382, 'â€œPalmifleur Maliboutâ€ - No.382');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15383, 'â€œPalmifleur Passaohâ€ - No.383');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15384, 'â€œPalmifleur Moritoâ€ - No.384');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15385, 'â€œCorailleurâ€ - No.385');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15386, 'â€œCorailleur Magistralâ€ - No.386');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15387, 'â€œTourbassingueâ€ - No.387');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15388, 'â€œBourbassingueâ€ - No.388');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15389, 'â€œLe Ouassingue EntourbÃ©â€ - No.389');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15390, 'â€œRoissingueâ€ - No.390');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15391, 'â€œKralamoure GÃ©antâ€ - No.391');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15392, 'â€œFloribondeâ€ - No.392');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15393, 'â€œBitouf Sombreâ€ - No.393');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15394, 'â€œBroutureâ€ - No.394');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15395, 'â€œFÃ©corceâ€ - No.395');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15396, 'â€œChiendentâ€ - No.396');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15397, 'â€œAbrakleur Sombreâ€ - No.397');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15398, 'â€œNerbeâ€ - No.398');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15399, 'â€œTynril ConsternÃ©â€ - No.399');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15400, 'â€œTynril DÃ©concertÃ©â€ - No.400');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15401, 'â€œTynril Perfideâ€ - No.401');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15402, 'â€œTynril Ahuriâ€ - No.402');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15403, 'â€œBitouf AÃ©rienâ€ - No.403');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15404, 'â€œPoolayâ€ - No.404');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15405, 'â€œAbrakleur Clairâ€ - No.405');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15406, 'â€œKaskargoâ€ - No.406');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15407, 'â€œMeupetteâ€ - No.407');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15408, 'â€œKimboâ€ - No.408');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15409, 'â€œSparoâ€ - No.409');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15410, 'â€œBarbroussaâ€ - No.410');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15411, 'â€œLe Flibâ€ - No.411');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15412, 'â€œGourlo le Terribleâ€ - No.412');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15413, 'â€œGamine Zothâ€ - No.413');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15414, 'â€œGuerrier Zothâ€ - No.414');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15415, 'â€œDisciple Zothâ€ - No.415');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15416, 'â€œSergent Zothâ€ - No.416');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15417, 'â€œMaÃ®tre Zothâ€ - No.417');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15418, 'â€œManitou Zothâ€ - No.418');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15419, 'â€œCooleuvreâ€ - No.419');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15420, 'â€œBulbifloreâ€ - No.420');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15421, 'â€œBulbuissonâ€ - No.421');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15422, 'â€œBamboutoâ€ - No.422');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15423, 'â€œBulbambouâ€ - No.423');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15424, 'â€œBulbigâ€ - No.424');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15425, 'â€œBambouto SacrÃ©â€ - No.425');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15426, 'â€œTanuki Chanâ€ - No.426');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15427, 'â€œKitsou Nakwaâ€ - No.427');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15428, 'â€œKitsou Nereâ€ - No.428');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15429, 'â€œKitsou Naeâ€ - No.429');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15430, 'â€œKitsou Nufeuâ€ - No.430');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15431, 'â€œPandawa Ivreâ€ - No.431');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15432, 'â€œPandalette Ivreâ€ - No.432');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15433, 'â€œTanukouÃ¯ Sanâ€ - No.433');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15434, 'â€œPanditâ€ - No.434');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15435, 'â€œPandikaze aÃ©rienâ€ - No.435');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15436, 'â€œPandikaze vertigeâ€ - No.436');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15437, 'â€œPandikwakazeâ€ - No.437');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15438, 'â€œPandulkazeâ€ - No.438');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15439, 'â€œGuerrier Pandikazeâ€ - No.439');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15440, 'â€œPanduleâ€ - No.440');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15441, 'â€œPandikazeâ€ - No.441');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15442, 'â€œMaÃ®tre Pandoreâ€ - No.442');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15443, 'â€œPandoreâ€ - No.443');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15444, 'â€œZillaâ€ - No.444');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15445, 'â€œYokai Firefouxâ€ - No.445');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15446, 'â€œSoryo Firefouxâ€ - No.446');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15447, 'â€œMaho Firefouxâ€ - No.447');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15448, 'â€œLÃ©opardoâ€ - No.448');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15449, 'â€œPÃ©ki PÃ©kiâ€ - No.449');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15450, 'â€œFantÃ´me Pandikazeâ€ - No.450');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15451, 'â€œFantÃ´me Maho Firefouxâ€ - No.451');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15452, 'â€œFantÃ´me Soryo Firefouxâ€ - No.452');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15453, 'â€œFantÃ´me LÃ©opardoâ€ - No.453');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15454, 'â€œFantÃ´me Yokai Firefouxâ€ - No.454');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15455, 'â€œFantÃ´me TanukouÃ¯ Sanâ€ - No.455');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15456, 'â€œFantÃ´me Panduleâ€ - No.456');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15457, 'â€œFantÃ´me Tanuki Chanâ€ - No.457');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15458, 'â€œFantÃ´me Pandoreâ€ - No.458');
INSERT INTO card_catalog (card_item_id, card_name) VALUES (15459, 'â€œCoffre Maudit du Flibâ€ - No.459');
